// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package queries

import (
	"context"
)

const createAUser = `-- name: CreateAUser :one
INSERT INTO users (
  email
) VALUES (
  $1
)
RETURNING id, email, phone, address, created_at, updated_at
`

func (q *Queries) CreateAUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createAUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
