basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Cupid Valentine
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: MIT
    url: https://www.mit.edu/~amini/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Go mangosteen API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 用来测试API是否正常工作
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: 用来测试API是否正常工作
      tags:
      - accounts
securityDefinitions:
  BasicAuth(JWT):
    type: basic
swagger: "2.0"
